Modified FizzBuzz.js
Saylee119/student-repo-fullstack pull request #1
Opened 2022-10-05 02:03 UTC by Saylee119

2022-10-05 22:53 UTC, juhiaugustine commented on hw1/01-fizzbuzz.js
> +      console.log("FizzBuzz");
F̵i̵z̵z̵B̵u̵z̵z̵ -> fizzbuzz

2022-10-05 22:53 UTC, juhiaugustine commented on hw1/01-fizzbuzz.js
> +      console.log("Fizz");
F̵i̵z̵z̵ ---> fizz

2022-10-05 22:54 UTC, juhiaugustine commented on hw1/01-fizzbuzz.js
> +      console.log("Buzz");
B̵u̵z̵z̵  --->  buzz

2022-10-05 22:56 UTC, juhiaugustine requested changes
Code looks good to me. Just the output string needs to be in lowercase.

2022-10-06 02:23 UTC, juhiaugustine approved these changes
Your code seems to be neat and good.

2022-10-06 06:09 UTC, smah29 approved these changes

2022-10-10 23:54 UTC, CzerPDX approved these changes
Code looks good! I like how you used if else here. My solution is much less efficient, this is very nice!

2022-10-20 00:16 UTC, merged